### PR TITLE
Kjq/update deps

### PR DESCRIPTION
**Pull request by kentquirk**
@jebeck -- just updated dependencies; all the tests still pass.

### CODE REVIEW

**Comment by jebeck** [comment]
Looks good.

Are we on the same page re: updating our usage of sundial everywhere else? My suggestion would be that we manually update the sundial usage first since we (I) know there are breaking changes, then do the general npm scrub.

**Comment by kentquirk** [comment]
I'm happy with that. Are you able to tackle the sundial fixes?

**Comment by jebeck** [comment]
Yeah, I can start working on those updates. Just clamshell and blip I think. Were you going to scrub those last though, if you're going bottom to top?

**Comment by kentquirk** [comment]
sundial is used in blip, clamshell, jellyfish, message-api, and the
uploader.

Only jellyfish, message-api and clamshell are still on a pre-1.0 version
(0.1.x).

blip and clamshell would be last, but jellyfish and message-api want to be
soon.



On Thu, Jan 29, 2015 at 8:36 PM, Jana Beck <notifications@github.com> wrote:

> Yeah, I can start working on those updates. Just clamshell and blip I
> think. Were you going to scrub those last though, if you're going bottom to
> top?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tidepool-org/sundial/pull/13#issuecomment-72139313>.
>



-- 
Kent Quirk
VP of Engineering, Tidepool

Tidepool is an open source, not-for-profit effort to build an open data
platform and better applications to reduce the burden of Type 1 Diabetes.

**Comment by jebeck** [comment]
OK, I can put on my list to start working on jellyfish and message-api. Do you have a preference which of those two goes first?

**Comment by kentquirk** [comment]
I'd prefer jellyfish first, please.

On Fri, Jan 30, 2015 at 1:35 PM, Jana Beck <notifications@github.com> wrote:

> OK, I can put on my list to start working on jellyfish and message-api. Do
> you have a preference which of those two goes first?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tidepool-org/sundial/pull/13#issuecomment-72247984>.
>



-- 
Kent Quirk
VP of Engineering, Tidepool

Tidepool is an open source, not-for-profit effort to build an open data
platform and better applications to reduce the burden of Type 1 Diabetes.

**Pull request merged**
